name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "enhancement"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        env:
          DEFAULT_ISSUE_ASSIGNEE: GITHUB_ACTOR
        with:
          assignees: ${{ vars.DEFAULT_ISSUE_ASSIGNEE }}
