name: Issue assignment

on:
  issues:
    types: 
      - opened
      - reopened

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: ${{ github.actor }}
                  numOfAssignee: 1
                  allowSelfAssign: true
